### ISSUE TITLE
MqttWildcard

### ISSUE THREAD

**Issue by LennartHennigs** [dersimn/ArduinoPubSubClientTools#2]
Hey Simon,
I find your implementation really really helpful.
The callbacks for subscribe and publish was exactly I was looking for.
So thanks a lot for this.

I have a small question though.
Could you provide an example for the MqttWildcard class you also have in here?
Thanks

Lennart

**Comment by dersimn** [comment]
It's used [here](https://github.com/dersimn/ArduinoPubSubClientTools/blob/bd93920665ffd80469324dd14949d2f20b21cea5/PubSubClientTools.cpp#L79) in the other .cpp File.

Just compare two Strings where one of them contains a wildcard like `foo/+/bar` and the other one the topic that you want to match like `foo/something/bar`:

```C++
if (MqttWildcard::wildcardMatch(topic_string, wildcard_string)) {
    // topic matches the wildcard
}
```
